language: python
sudo: false

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 3.7
          env: TOXENV=py37

install:
    - pip install -r requirements.txt
script:
    - ./.travis/run.sh
notifications:
    email: false
